window.PopupDom = {
	runButton: document.getElementById("runButton"),
	recentButton: document.getElementById("recentButton"),
	settingsButton: document.getElementById("settingsButton"),
	initialView: document.getElementById("initialView"),
	changesView: document.getElementById("changesView"),
	settingsView: document.getElementById("settingsView"),
	backToInitialButton: document.getElementById("backToInitialButton"),
	backFromSettingsButton: document.getElementById("backFromSettingsButton"),
	saveSettingsButton: document.getElementById("saveSettingsButton"),
	clearSettingsButton: document.getElementById("clearSettingsButton"),
	tokenNameInput: document.getElementById("tokenNameInput"),
	tokenValueInput: document.getElementById("tokenValueInput"),
	organizationInput: document.getElementById("organizationInput"),
	projectSelect: document.getElementById("projectSelect"),
	teamSelect: document.getElementById("teamSelect"),
	settingsStatus: document.getElementById("settingsStatus"),
	result: document.getElementById("result"),
	sprintSelect: document.getElementById("sprintSelect"),
	includeCurrentDayToggle: document.getElementById("includeCurrentDayToggle"),
	recentList: document.getElementById("recentList"),
	recentSection: document.getElementById("recentSection"),
	detailSection: document.getElementById("detailSection"),
	backArrowButton: document.getElementById("backArrowButton"),
	detailOpenLinkButton: document.getElementById("detailOpenLinkButton"),
	detailMeta: document.getElementById("detailMeta"),
	detailDescription: document.getElementById("detailDescription"),
};
