window.PopupState = {
	lastWindowScrollTop: 0,
	currentDetailItemId: "",
	currentDetailItemUrl: "",
	currentListMode: "recent",
	currentListItems: [],
	currentListPage: 1,
	itemsPerPage: 10,
	currentProjectStatusMapping: null,
	statusMappingDraft: null,
	draggingStatusName: "",
	availableProjectStates: [],
	availableProjectWorkItemTypes: [],
	hasCompleteSettings: false,
	availableTokens: [],
	availableUsers: [],
	activeProfile: "analyst",
	settingsDraftProfile: "analyst",
	managementSelectedUserId: "",
	confirmationResolver: null,
	tokenSettingsByTokenId: {},
	settingsSavedSignature: "",
	loadingRequests: 0,
	shouldReloadMetricsAfterTokenDeletion: false,
	isRestoringUiState: false,
};
